// src/routes/details/[id]/+page.svelte
<script>
	// @ts-nocheck
	// Modals Utils
	import Videoplayer from '$lib/components/Videoplayer.svelte';
	import { Tabs, TabItem } from 'flowbite-svelte';
	import { AccordionItem, Accordion } from 'flowbite-svelte';

	import { modalvideo, omulist, noomulist, seriestype } from '$lib/modalPropsStore';
	let myPlaylist = [];
	let myPlaylistomu = [];

	let showvideo = false;
	export let data;
	$: data1 = data.article;
	let tabSet = 0;
	console.log(data.article);
	function playvideo() {
		seriestype.set('');
		let poster1;
		if (data1.backdrop) {
			poster1 = 'https://img.mediathek.community/t/p/original/' + data1.backdrop;
		} else {
			poster1 = 'https://img2.mediathek.community/assets/' + data1.heroimage;
		}
		showvideo = true;
		//console.log(data1);
		if (data1.directlink) {
			modalvideo.set({
				source: [{ src: data1.directlink, type: data1.format }],
				type: data1.format,
				poster: poster1,
				title: data1.title
			});
		} else {
			let sources = [];
			if (data1.directlinkfhd) {
				sources.push({
					src: data1.directlinkfhd,
					type: data1.format,
					res: '1080',
					label: '1080p',
					default: true
				});
			}
			if (data1.directlinkhd) {
				sources.push({
					src: data1.directlinkhd,
					type: data1.format,
					res: '720',
					label: '720p'
				});
			}
			if (data1.directlinkmd) {
				sources.push({
					src: data1.directlinkmd,
					type: data1.format,
					res: '480',
					label: '480p'
				});
			}
			if (data1.directlinklq) {
				sources.push({
					src: data1.directlinklq,
					type: data1.format,
					res: '360',
					label: '360p'
				});
			}
			modalvideo.set({
				source: sources,
				type: data1.format,
				poster: poster1,
				title: data1.title
			});
			//console.log($modalvideo);
		}
	}
	function playepisode(alldata, type) {
		myPlaylist = [];
		myPlaylistomu = [];
		seriestype.set(type);
		for (let i = 0; i < data1.listepisodes.length; i++) {
			if (data1.listepisodes[i].omu == false) {
				let sources = [];
				if (data1.listepisodes[i].directlinkfhd) {
					sources.push({
						src: data1.listepisodes[i].directlinkfhd,
						type: data1.listepisodes[i].format,
						res: '1080',
						label: '1080p',
						default: true
					});
				}
				if (data1.listepisodes[i].directlinkhd) {
					sources.push({
						src: data1.listepisodes[i].directlinkhd,
						type: data1.listepisodes[i].format,
						res: '720',
						label: '720p'
					});
				}
				if (data1.listepisodes[i].directlinkmd) {
					sources.push({
						src: data1.listepisodes[i].directlinkmd,
						type: data1.listepisodes[i].format,
						res: '480',
						label: '480p'
					});
				}
				if (data1.listepisodes[i].directlinklq) {
					sources.push({
						src: data1.listepisodes[i].directlinklq,
						type: data1.listepisodes[i].format,
						res: '360',
						label: '360p'
					});
				}

				myPlaylist.push({
					title: data1.listepisodes[i].Title,
					infoTitle: data1.listepisodes[i].Title,
					poster: 'https://img.mediathek.community/t/p/original/' + data1.backdrop,
					sources: sources
				});
			} else {
				let sources = [];
				if (data1.listepisodes[i].directlinkfhd) {
					sources.push({
						src: data1.listepisodes[i].directlinkfhd,
						type: data1.listepisodes[i].format,
						res: '1080',
						label: '1080p',
						default: true
					});
				}
				if (data1.listepisodes[i].directlinkhd) {
					sources.push({
						src: data1.listepisodes[i].directlinkhd,
						type: data1.listepisodes[i].format,
						res: '720',
						label: '720p'
					});
				}
				if (data1.listepisodes[i].directlinkmd) {
					sources.push({
						src: data1.listepisodes[i].directlinkmd,
						type: data1.listepisodes[i].format,
						res: '480',
						label: '480p'
					});
				}
				if (data1.listepisodes[i].directlinklq) {
					sources.push({
						src: data1.listepisodes[i].directlinklq,
						type: data1.listepisodes[i].format,
						res: '360',
						label: '360p'
					});
				}
				myPlaylistomu.push({
					title: 'omu' + data1.listepisodes[i].Title,
					infoTitle: data1.listepisodes[i].Title,
					poster: 'https://img.mediathek.community/t/p/original/' + data1.backdrop,
					sources: sources
				});
			}
		}
		noomulist.set(myPlaylist);
		omulist.set(myPlaylistomu);
		showvideo = true;
	}
</script>

{#if data.article}
	<div>
		{#if showvideo != true}
			{#if data1.backdrop != 'backdrop' && data1.backdrop}
				<img
					class="rounded-lg max-h-fit mx-auto relative"
					src="https://img.mediathek.community/t/p/original{data1.backdrop}"
					alt="description"
				/>
			{:else}
				<img
					class="rounded-lg max-h-fit mx-auto relative"
					src="https://api.mediathek.community/assets/{data1.coverimage}"
					alt="description"
				/>{/if}
		{:else}
			<div class="max-h-fit grid place-items-center">
				<svelte:component this={Videoplayer} />
			</div>
		{/if}
	</div>
	<Tabs style="underline" class="px-2">
		<TabItem open>
			<div slot="title" class="flex items-center gap-2">
				Details
			</div>
			<div class=" shadow-md sm:rounded-lg">
				<table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
					<tbody>
						<tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
							<th
								scope="row"
								class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
							>
								Sender
							</th>
							<td class="px-6 py-4">
								{data1.channel}
							</td>
						</tr>
						{#if data1.category == 'series'}
							<tr class="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
								<th
									scope="row"
									class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
								>
									Staffeln
								</th>
								<td class="px-6 py-4">
									{data1.episodes}
								</td>
							</tr>
							<tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
								<th
									scope="row"
									class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
								>
									Folgen
								</th>
								<td class="px-6 py-4">
									{data1.listepisodes.length}
								</td>
							</tr>
						{/if}
						<tr class="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
							<th
								scope="row"
								class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
							>
								Quality
							</th>
							<td class="px-6 py-4">
								{data1.quality}
							</td>
						</tr>
						<tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
							<th
								scope="row"
								class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
							>
								description
							</th>
							<td class="px-6 py-4">
								{data1.description}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</TabItem>
		{#if data1.category != 'series'}
			<TabItem>
				<div slot="title" class="flex items-center gap-2">
					Links
				</div>
				<div class=" shadow-md sm:rounded-lg">
					<table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
						<tbody>
							<tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
								<th
									scope="row"
									class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
								>
									Direktlink
								</th>
								<td class="px-4 py-2">
									<button type="button" class="btn variant-filled mt-0" on:click={playvideo}
										>play</button
									>
								</td>
							</tr>
							{#if data1.detailslink}
								<tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
									<th
										scope="row"
										class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
									>
										Direktlink 2
									</th>
									<td class="px-4 py-2">
										<a href={data1.detailslink} target="_blank">
											<button type="button" class="btn variant-filled mt-0">Detailseite</button>
										</a>
									</td>
								</tr>
							{/if}
						</tbody>
					</table>
				</div>
			</TabItem>
		{:else}
			<TabItem>
				<div slot="title" class="flex items-center gap-2">
					Episoden
				</div>
				<Accordion>
					{#each data1.listepisodes as episode}
						{#if episode.omu == false}
							<AccordionItem>
								<svelte:fragment slot="header">{episode.Title}</svelte:fragment>
								<div class="grid grid-cols-4 grid-rows-1 gap-0 flex">
									<div class="col-span-3">{episode.description}</div>
									<div class="col-span-1 justify-center items-center flex">
										<button
											type="button"
											class="btn variant-filled"
											on:click={playepisode(episode, 'noomu')}>Play</button
										>
									</div>
								</div>
							</AccordionItem>
						{/if}
					{/each}
				</Accordion>
			</TabItem>
			<TabItem>
				<div slot="title" class="flex items-center gap-2">
					Episoden-OmU
				</div>
				<Accordion>
					{#each data1.listepisodes as episode}
						{#if episode.omu == true}
							<AccordionItem>
								<svelte:fragment slot="header">{episode.Title}</svelte:fragment>
								<div class="grid grid-cols-4 grid-rows-1 gap-0 flex">
									<div class="col-span-3">{episode.description}</div>
									<div class="col-span-1 justify-center items-center flex">
										<button
											type="button"
											class="btn variant-filled"
											on:click={playepisode(episode, 'noomu')}>Play</button
										>
									</div>
								</div>
							</AccordionItem>
						{/if}
					{/each}
				</Accordion>
			</TabItem>
		{/if}
	</Tabs>
	<!-- 
	<TabGroup justify="justify-center">
 
			<Tab bind:group={tabSet} name="tab4" value={3}>Episoden-OmU</Tab>
		{/if}
 		<svelte:fragment slot="panel">
 
			{:else if tabSet === 3}
				<Accordion>
					{#each data1.listepisodes as episode}
						{#if episode.omu == true}
							<AccordionItem>
								<svelte:fragment slot="summary">{episode.Title}</svelte:fragment>
								<svelte:fragment slot="content">
									<div class="grid grid-cols-4 grid-rows-1 gap-0 flex">
										<div class="col-span-3">{episode.description}</div>
										<div class="col-span-1 justify-center items-center flex">
											<button
												type="button"
												class="btn variant-filled"
												on:click={playepisode(episode, 'noomu')}>Play</button
											>
										</div>
									</div>
								</svelte:fragment>
							</AccordionItem>
						{/if}
					{/each}
				</Accordion>
			{/if}
		</svelte:fragment>
	</TabGroup>
-->
{:else}
	<h1 class="h1">
		<span
			class="bg-gradient-to-br from-pink-100 to-red-900 bg-clip-text text-transparent box-decoration-clone"
			>No Item(s) found for category:</span
		>
		{data.param}
	</h1>
{/if}

// pages/details/[id].vue
<template>
  <UPage>
    <UAlert v-if="alert" :icon="alert.icon" :color="alert.color" :variant="alert.variant" :title="alert.title"
      :description="alert.description" />
    <div class=" h-image1 mx-auto grid place-items-center">
      <div class="">
 			<div v-if=!showvideo class=" h-image1 mx-auto grid place-items-center">
        <img :src="showflag1(data)" alt="image" />
			</div>
	 
			<div v-if=showvideo class="h-image1 mx-auto grid place-items-center">
        <Videoplayer :vdata="modalvideo" />
  			</div>
 	</div>
    </div>
    <UDivider label="-" />

    <UTabs :items="items" class="w-full">
      <template #default="{ item, index, selected }">
        <div class="flex items-center gap-2 relative truncate">
          <UIcon :name="item.icon" class="w-4 h-4 flex-shrink-0" />

          <span class="truncate">{{ index + 1 }}. {{ item.label }}</span>

          <span v-if="selected" class="absolute -right-4 w-2 h-2 rounded-full bg-primary-500 dark:bg-primary-400" />
        </div>
      </template>
      <template #item="{ item }">
        {{ item }}
        {{ data[item.key] }}
        <div class=" shadow-md sm:rounded-lg">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <tbody>
              <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  Play
                </th>
                <td class="px-4 py-2">
                  <button type="button" class="btn variant-filled mt-0" @click.prevent=playvideo()>
                    Play
                  </button>
                </td>
              </tr>
              <tr v-if="data.detailslink" class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  Direktlink
                </th>
                <td class="px-4 py-2">
                  <a :href=data.detailslink target="_blank">
                    <button type="button" class="btn variant-filled mt-0">Detailseite</button>
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </template>
    </UTabs>

  </UPage>
</template>

<script lang="ts" setup>
let alert = computed(() => {
  var x = undefined
  if (data.channel == 'rai') {
    x = {
      icon: 'i-heroicons-command-line',
      color: 'green',
      variant: 'subtle',
      title: 'Info',
      description: 'You can add components to your app using the cli.'
    }
  }
  if (data.channel == 'svt') {
    x = {
      icon: 'i-heroicons-command-line',
      color: 'blue',
      variant: 'subtle',
      title: 'Info',
      description: 'Select "Tydligare tal" as audio language for English audio'
    }
  }
  if (data.quality == 'uhd') {
    x = {
      icon: 'i-heroicons-command-line',
      color: 'red',
      variant: 'subtle',
      title: 'Heads up!',
      description: 'UHD ist aktuell buggy im Edge Browser - nehmt besser Chrome'
    }
  }
  return x
})
let myPlaylist = [];
let showvideo = ref(false);
let imgsrc1;
let d1;
let keyz;
let omulist1;
let omulist2;
let episodelist;
let modalvideo = ref();
let data = ref();
let data2 = ref();
const route = useRoute()

data = await $fetch('/api/details/' + route.params.id)
data2 = data
data = data.all[0]


const items = computed(() => {
  let x = []
  x.push({
    label: 'Details',
    icon: 'i-heroicons-information-circle',
    key: 'title',
  })
  if (data.category != 'series') {
    x.push({
      label: 'Links',
      icon: 'i-heroicons-information-circle',
      key: 'links',
    })
  }
  return x
})
 function showflag1(data) {
  return data.poster ? 'https://img.mediathek.community/t/p/original/' + data.backdrop : 'https://img2.mediathek.community/assets/' + data.coverimage
}
function playvideo() {
  let poster1;
  if (data.backdrop) {
    poster1 = 'https://img.mediathek.community/t/p/original/' + data.backdrop;
  } else {
    poster1 = 'https://img2.mediathek.community/assets/' + data.heroimage;
  }
  showvideo.value = true;
  //console.log(data1);
  if (data.medialink) {
    modalvideo = {
      source: [{ src: data.medialink, type: data.format }],
      type: data.format,
      poster: poster1,
      title: data.title
    }
  } else {
    let sources = [];
    if (data.directlinkfhd) {
      sources.push({
        src: data.directlinkfhd,
        type: data.format,
        res: '1080',
        label: '1080p',
        default: true
      });
    }
    if (data.directlinkhd) {
      sources.push({
        src: data.directlinkhd,
        type: data.format,
        res: '720',
        label: '720p'
      });
    }
    if (data.directlinkmd) {
      sources.push({
        src: data.directlinkmd,
        type: data.format,
        res: '480',
        label: '480p'
      });
    }
    if (data.directlinklq) {
      sources.push({
        src: data.directlinklq,
        type: data.format,
        res: '360',
        label: '360p'
      });
    }
    modalvideo.set({
      source: sources,
      type: data.format,
      poster: poster1,
      title: data.title
    });
    //console.log($modalvideo);
  }
}
</script>

<style>
.h-image1 {
  max-width: 54rem !important;
  height: auto !important;
}
</style>
